// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'ecommerce_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String APP_ICON_BACKGROUND = 'assets/app-icon-background.png';
  static const String APP_ICON_FOREGROUND = 'assets/app-icon-foreground.png';
  static const String APP_ICON = 'assets/app-icon.png';
  static const String LICENSE = 'assets/fonts/LICENSE.txt';
  static const String BRUSCHETTA_PLATE = 'assets/products/bruschetta-plate.jpg';
  static const String FLOWERS_PLATE = 'assets/products/flowers-plate.jpg';
  static const String HONEY_POT = 'assets/products/honey-pot.jpg';
  static const String JUICER_CITRUS_FRUITS = 'assets/products/juicer-citrus-fruits.jpg';
  static const String MOZZARELLA_PLATE = 'assets/products/mozzarella-plate.jpg';
  static const String PASTA_PLATE = 'assets/products/pasta-plate.jpg';
  static const String PIGGY_BLUE = 'assets/products/piggy-blue.jpg';
  static const String PIGGY_GREEN = 'assets/products/piggy-green.jpg';
  static const String PIGGY_PINK = 'assets/products/piggy-pink.jpg';
  static const String PIZZA_PLATE = 'assets/products/pizza-plate.jpg';
  static const String PLATE_AND_BOWL = 'assets/products/plate-and-bowl.jpg';
  static const String SALT_PEPPER_LEMON = 'assets/products/salt-pepper-lemon.jpg';
  static const String SALT_PEPPER_OLIVES = 'assets/products/salt-pepper-olives.jpg';
  static const String SNACKS_PLATE = 'assets/products/snacks-plate.jpg';
}
